version: "3.0"
services:
  produto-service:
    image: disciplinaservice
    build:
      context: ../disciplina-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - eureka-net

networks:
  eureka-net:
